name: '04.homework C++ SFINAE'

on:
  push:
    branches:
      - 04.homework
      - feature/github_actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: cmake .
      - run: cmake --build .
      - run: cmake --build . --target package
      - name: Generate build number
        id: buildnumber
        uses: onyxmueller/build-tag-number@v1
        with:
          token: ${{ secrets.github_token }}
          prefix: ${{ github.github.ref_name }}

      - name: Get commit count
        run:  git checkout 04.homework | git rev-list --count HEAD ^04.homework

      - name: Print new build number
        run: echo "Build number is ${{ steps.buildnumber.outputs.build_number }}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release SFINAE ${{ env.BUILD_NUMBER }}
          draft: false
          prerelease: false

      - name: Rename create file
        run: mv sfinae-0.0.1-Linux.deb sfinae-0.0.${{ env.BUILD_NUMBER }}-Linux.deb

      - name: List directory
        run: ls -a

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./sfinae-0.0.${{ env.BUILD_NUMBER }}-Linux.deb
          asset_name: sfinae-0.0.${{ env.BUILD_NUMBER }}-Linux.deb
          asset_content_type: application/vnd.debian.binary-package